#include "tim.h"
#define TIM2EN (1U<<0)
#define CR1_CEN (1U<<0)
// TIMER CLOCK IS 10KHZ
void tim2_1hz_init(void){
//	enable clock access to tim2
	RCC->APB1ENR |= TIM2EN; // ENABLE CLOCK FOR TIM2
	TIM2->PSC = 1600-1; // SETS PRESCALER

	TIM2->ARR = 10000-1; // SETS AUTO RELOAD VALUE
	TIM2->CNT = 0;  // CLEARS THE COUNTER TO ENSURES COUNTER START FROM 0 WHEN WE ENABLE IT ;

//	ENABLE TIMER
	TIM2->CR1 |= CR1_CEN; // ENABLE CONTROL REGISTER 1 FOR TIM2
	// THE ABOVE LINE STARTS THE TIMER AND BEGIN THE COUNTING

}


//SUMMARY
/*
 * 	ENABLES THE CLOCK FOR TIM2
 * 	SETS A PRESCALER AND AUTO RELOAD VALUE
 * CLEAR THE COUNTER
 * ENABLES THE TIMER

 * */











